# .graphclientrc.yml
sources:
  - name: super-auction
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/godzillaba/super-auction-test2

documents:
  - ./queries.graphql